/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 * La clase Menu representa la ventana principal del menú de la aplicación.
 * 
 * @author Christian
 */
public class Menu extends javax.swing.JFrame {

    public static Welcome v1;

    /**
     * Constructor de la clase Menu. Inicializa la interfaz de usuario y oculta
     * la ventana de bienvenida asociada.
     *
     * @param v1 Instancia de la clase Welcome que se asocia a esta ventana de
     * menú.
     */
    public Menu(Welcome v1) {
        initComponents();
        this.v1 = v1;
        v1.setVisible(false);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        checkIn = new javax.swing.JButton();
        checkOut = new javax.swing.JButton();
        searchRes = new javax.swing.JButton();
        history = new javax.swing.JButton();
        searchLod = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        checkin_icon = new javax.swing.JLabel();
        searchLodging_icon = new javax.swing.JLabel();
        history_icon = new javax.swing.JLabel();
        checkout_icon = new javax.swing.JLabel();
        searchReservation_icon = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar Reservación:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, 20));

        jLabel2.setFont(new java.awt.Font("Britannic Bold", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Escoge una opción:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        checkIn.setBackground(new java.awt.Color(0, 0, 0));
        checkIn.setForeground(new java.awt.Color(255, 255, 255));
        checkIn.setText("Check In");
        checkIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInActionPerformed(evt);
            }
        });
        jPanel1.add(checkIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 90, 40));

        checkOut.setBackground(new java.awt.Color(0, 0, 0));
        checkOut.setForeground(new java.awt.Color(255, 255, 255));
        checkOut.setText("Check Out");
        checkOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutActionPerformed(evt);
            }
        });
        jPanel1.add(checkOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 90, 40));

        searchRes.setBackground(new java.awt.Color(0, 0, 0));
        searchRes.setForeground(new java.awt.Color(255, 255, 255));
        searchRes.setText("Buscar");
        searchRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchResActionPerformed(evt);
            }
        });
        jPanel1.add(searchRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 90, 40));

        history.setBackground(new java.awt.Color(0, 0, 0));
        history.setForeground(new java.awt.Color(255, 255, 255));
        history.setText("Historial");
        history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyActionPerformed(evt);
            }
        });
        jPanel1.add(history, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 90, 40));

        searchLod.setBackground(new java.awt.Color(0, 0, 0));
        searchLod.setForeground(new java.awt.Color(255, 255, 255));
        searchLod.setText("Buscar");
        searchLod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchLodActionPerformed(evt);
            }
        });
        jPanel1.add(searchLod, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 90, 40));

        jLabel3.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Check In:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Check Out:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Historial de habitación:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        jLabel7.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Buscar hospedaje:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));

        checkin_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checkin.png"))); // NOI18N
        jPanel1.add(checkin_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, 70));

        searchLodging_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/searchlodging.png"))); // NOI18N
        jPanel1.add(searchLodging_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, -1, 70));

        history_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/history.png"))); // NOI18N
        jPanel1.add(history_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, -1, 70));

        checkout_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checkout.png"))); // NOI18N
        jPanel1.add(checkout_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, 70));

        searchReservation_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/searchreservation.png"))); // NOI18N
        jPanel1.add(searchReservation_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, 70));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 440));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método invocado al hacer clic en el botón "Check-In". Crea una instancia
     * de la ventana CheckIn y la muestra. Oculta la ventana actual de menú.
     *
     * @param evt El evento de acción generado al hacer clic en el botón
     * "Check-In".
     */
    private void checkInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInActionPerformed
        CheckIn checkin = new CheckIn(this);
        this.setVisible(false);
        checkin.setVisible(true);
    }//GEN-LAST:event_checkInActionPerformed
    /**
     * Método invocado al hacer clic en el botón "Historial". Crea una instancia
     * de la ventana History y la muestra. Oculta la ventana actual de menú.
     *
     * @param evt El evento de acción generado al hacer clic en el botón
     * "Historial".
     */
    private void historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyActionPerformed
        History history = new History(this);
        this.setVisible(false);
        history.setVisible(true);
    }//GEN-LAST:event_historyActionPerformed
    /**
     * Método invocado al hacer clic en el botón "Buscar Reservas". Crea una
     * instancia de la ventana SearchReservation y la muestra. Oculta la ventana
     * actual de menú.
     *
     * @param evt El evento de acción generado al hacer clic en el botón "Buscar
     * Reservas".
     */
    private void searchResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchResActionPerformed
        SearchReservation searchRes = new SearchReservation(this);
        this.setVisible(false);
        searchRes.setVisible(true);
    }//GEN-LAST:event_searchResActionPerformed
    /**
     * Método invocado al hacer clic en el botón "Check-Out". Crea una instancia
     * de la ventana CheckOut y la muestra. Oculta la ventana actual de menú.
     *
     * @param evt El evento de acción generado al hacer clic en el botón
     * "Check-Out".
     */
    private void checkOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutActionPerformed
        CheckOut checkout = new CheckOut(this);
        this.setVisible(false);
        checkout.setVisible(true);
    }//GEN-LAST:event_checkOutActionPerformed
    /**
     * Método invocado al hacer clic en el botón "Buscar Hospedajes". Crea una
     * instancia de la ventana SearchLodging y la muestra. Oculta la ventana
     * actual de menú.
     *
     * @param evt El evento de acción generado al hacer clic en el botón "Buscar
     * Hospedajes".
     */
    private void searchLodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchLodActionPerformed
        SearchLodging searchLod = new SearchLodging(this);
        this.setVisible(false);
        searchLod.setVisible(true);
    }//GEN-LAST:event_searchLodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu(v1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton checkIn;
    private javax.swing.JButton checkOut;
    private javax.swing.JLabel checkin_icon;
    private javax.swing.JLabel checkout_icon;
    private javax.swing.JButton history;
    private javax.swing.JLabel history_icon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton searchLod;
    private javax.swing.JLabel searchLodging_icon;
    private javax.swing.JButton searchRes;
    private javax.swing.JLabel searchReservation_icon;
    // End of variables declaration//GEN-END:variables
}
